name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    name: "Lint (standardrb)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4
          bundler-cache: true

      - name: Lint code for consistent style
        run: bundle exec standardrb

  test:
    name: "Tests (${{ matrix.rails }}, ${{ matrix.database.name }})"
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.rails }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        rails:
          - rails_7
          - rails_8
        database:
          - { name: 'PostgreSQL', url: 'postgresql://postgres:postgres@localhost:5432/geneva_drive_test' }
          - { name: 'MySQL', url: 'mysql2://root:root@127.0.0.1:3306/geneva_drive_test?encoding=utf8mb4' }
          - { name: 'SQLite', url: 'sqlite3:test/dummy/db/test.sqlite3' }

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: geneva_drive_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: geneva_drive_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config libsqlite3-dev

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4
          bundler-cache: true

      - name: Generate migrations
        run: bundle exec rails generate geneva_drive:install --skip
        working-directory: test/dummy

      - name: Setup database
        env:
          RAILS_ENV: test
          DATABASE_URL: ${{ matrix.database.url }}
        run: |
          bundle exec rails db:create || true
          bundle exec rails db:migrate
        working-directory: test/dummy

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: ${{ matrix.database.url }}
        run: bundle exec ruby -Itest bin/test
